baseURL = "http://www.vibhasgoyal.com"
title = "Vigo's Blog"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = "UA-64881400-2"

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt
enableEmoji = true
# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Build the future. Technology, Business, Design and Psychology"
title404 = "This content is not available in your country."

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Vibhas Goyal ( vibhas77 )"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
taxonomyCloudShuffle = true

[params.sidebar]
enable = true
sticky = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","twitter_follow","share_sidebar","taxonomy_cloud","recent_posts_sidebar","social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "vibhas77" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params]
    addThis = "ra-50594cfb1c07b16f"


[params.social]
email = "vibhas777@gmail.com"
facebook = "vibhas.goyal"
github = "vibhas77"
gitlab = "vibhas77"
instagram = "the_crazzy_vigo"
twitter = "vibhas77"

[params.social.config]
platforms = ["github","twitter","instagram","email","gitlab"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[[menu.main]]
name = "Home"
weight = -200
identifier = "home"
url = "/"

[[menu.main]]
name = "Posts"
weight = -150
identifier = "posts"
url = "/posts/"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
